M48
; DRILL file {KiCad (6.0.7)} date Tue Jun 10 03:22:08 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-10T03:22:08+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.1663Y-4.7878
X4.1663Y-5.0154
X5.2825Y-4.7878
X5.2825Y-5.0154
T2
X4.9557Y-5.0474
X5.0738Y-5.0474
T0
M30
